{
 "title": "New dashboard Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU utilisation"
    }
   ]
  },
  {
   "title": "CPU Load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA_1" },
    { "expr": "node_load5", "legendFormat": "CPULA_5" },
    { "expr": "node_load15", "legendFormat": "CPULA_15" }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Memory free" }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\"}",
     "legendFormat": "/dev/sda3"
    }
   ]
  }
 ]
}